#!/bin/sh
#
# Hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# Hook runs linting on all .js files and ensure that code is written 
# following the ES6 standard, commit will stop and log the linting errors
# in log file if necessary, othersiwe continue with the commit

FMT_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.js')
# Start the lint check.

set -e  # about hook command at first error

echo 'Start lint check'
deno lint --unstable # runs deno linting on all files in any directory 
 
if test ${#FMT_FILES} -gt 0
then
	echo 'Start code formatter'

	for FILE in $FMT_FILES
	do
		deno fmt $FILE # runs code formatter to improve code readability
  	done

else
	echo 'There is no JS file to check'
fi

exit 0


 