#!/bin/sh
#
# Hook script to prepare the commit log message.
# Called by "git commit" with the name of the file that has the
# commit message, before the commit message a custom string is addded
# which reflects the name of the user who is performing the commit
# this is also used as a method of signing off the message. 
# The hook's purpose is to edit the commit
# message file.  If the hook fails with a non-zero status,
# the commit is aborted.

set -e  # about hook command at first error

COMMIT_MSG_FILE=$1

AUTH="-Harman:"

sed -i.old "1s/^/ $AUTH \n /" "$COMMIT_MSG_FILE"

exit 0
